version: '3.9'

services:
  message-pickup-repository:
    build: .
    image: message-pickup-repository:test
    container_name: message-pickup-repository
    environment:
      - LOG_LEVEL=3
      - APP_PORT=3500
      - WS_PORT=3100
      - MONGODB_URI=mongodb://cloud-agent:cloud-agent@mongodb:27017/MessagePickupRepository
      - REDIS_TYPE=cluster
      - REDIS_NODES=192.168.10.13:6371,192.168.10.13:6372,192.168.10.13:6373,192.168.10.13:6374,192.168.10.13:6375,192.168.10.13:6376
      - REDIS_NATMAP=172.29.0.2:6379:192.168.10.13:6371,172.29.0.3:6379:192.168.10.13:6372,172.29.0.4:6379:192.168.10.13:6373,172.29.0.5:6379:192.168.10.13:6374,172.29.0.6:6379:192.168.10.13:6375,172.29.0.7:6379:192.168.10.13:6376
      - REDIS_URL=redis://redis:6379
    restart: always
    ports:
      - 3500:3500
      - 3100:3100
    networks:
      - loadbalancing
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cloud-agent
      - MONGO_INITDB_ROOT_PASSWORD=cloud-agent
      - MONGO_INITDB_DATABASE=admin
    ports:
      - '27017:27017'
    networks:
      - loadbalancing
    volumes:
      - ~/data/mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://cloud-agent:cloud-agent@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - loadbalancing

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - loadbalancing
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

networks:
  loadbalancing:
    external: true
