name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout message-pickup-repository
        uses: actions/checkout@v4

      - name: Setup node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          yarn install

      - name: Check Format
        run: |
          yarn format

      - name: Check Types
        run: |
          yarn check-types

      - name: Unit tests
        run: |
          yarn test

      - name: E2E tests
        run: |
          yarn test:e2e

  release-please:
    runs-on: ubuntu-latest
    #needs: [build]
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      paths_released: ${{ steps.release-please.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          path: ./packages
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: chore/monorepo-build-setup
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo ${{ toJson(steps.release-please.outputs) }}
        
